import type { DevLogEntry } from "@/lib/dev-log/types";

export const entry: DevLogEntry = {
    id: "2026-06-18-campaign-engine-v1-complete",
    date: "2026-06-18",
    title: "Campaign Narrative Engine v1 完成 — 5 阶段 18 计划 143 测试",
    summary: "经过 5 个阶段的系统化执行，Jity Campaign Narrative Engine v1 正式完成。实现了从基础技术栈升级到 AI 战役生成、锚点事件系统、叙事健康监控的完整闭环，auto_play.py 270 回合无崩溃通过。",
    developer: "TandyBlow",
    areas: ["backend", "frontend", "campaign", "llm", "rag", "testing", "ui", "milestone"],
    changes: [
      "Phase 1 Foundation（4 plans）：FastAPI/Pydantic/FAISS 升级、openai SDK 替换 httpx + json_repair、tiktoken token 计数、transitions FSM、Tailwind CSS v4 + shadcn/ui。",
      "Phase 2 Campaign Core（5 plans）：campaign.json 标准化格式 + v1→v2→v3 迁移链、CampaignManager 加载/校验/开场覆盖、独立 campaign_progress 表 + FSM 集成、锚点事件系统（混合触发器 + 单锚点/回合 + 冷却）、CampaignManager 上下文注入 + token 预算检查。",
      "Phase 3 Narrative Quality（4 plans）：Session 前情提要（LLM 压缩 'Previously on...'）、AI 战役生成（deepseek-v4-pro）+ 前端策展编辑器、动态分支检测（LLM fact extraction 替代硬编码关键词）、叙事健康监控 + 隐式引导注入。",
      "Phase 4 UI & Polish（2 plans）：发现时间线 UI（system-known vs player-confirmed 区分）、策展编辑器增强。",
      "Phase 5 Pre-Launch Hardening（3 plans）：context_strategy 接口、RAG embedding 升级（hash-based → DeepSeek embedding API）、选项策略配置化、并发安全（乐观锁）、auto_play.py 270 回合验证通过（3 arcs × 3 sessions × 30 turns）。",
      "schemas/ 包拆分：game.py（144 行）+ campaign.py（179 行），从单一 300+ 行文件重构。",
      "PromptBuilder 重构：PromptInput dataclass（6 参数→1 参数）、消息历史注入、风格锚点、负面约束指令。",
      "143 个 pytest 测试全部通过，覆盖 CampaignManager、FSM、锚点系统、schema 迁移、token 预算、前情提要、fact extraction、健康监控。",
      "DeepSeek 模型迁移：deepseek-chat → deepseek-v4-flash（日常）/ deepseek-v4-pro（创意生成）。",
    ],
    relatedFiles: [
      "backend/app/services/campaign_manager.py",
      "backend/app/services/campaign_fsm.py",
      "backend/app/services/campaign_generator.py",
      "backend/app/services/scenario_generator.py",
      "backend/app/services/prompt_builder.py",
      "backend/app/services/llm_client.py",
      "backend/app/services/game_state.py",
      "backend/app/services/retriever.py",
      "backend/app/services/embedding_client.py",
      "backend/app/services/health_monitor.py",
      "backend/app/services/context_strategy.py",
      "backend/app/schemas/game.py",
      "backend/app/schemas/campaign.py",
      "backend/tests/*.py",
      "frontend/src/app/curator/page.tsx",
      "frontend/src/app/timeline/page.tsx",
      "frontend/src/app/page.tsx",
      "scripts/auto_play.py",
    ],
    nextSteps: [
      "进入 v1.5（Phase 6-8）：Session 自动推进 + Arc 选择 + 小说管线 + 龙族内容包。",
      "解决已知 Blocker：Campaign 系统端到端 HTTP 验证、session_messages 表结构调整、_is_first_turn_of_session() 修复。",
    ],
  };
