import type { DevLogEntry } from "@/lib/dev-log/types";

export const entry: DevLogEntry = {
  id: "2026-10-01-campaign-memory-consistency",
  date: "2026-10-01",
  title: "战役唯一入口、分支记忆一致性与终局恢复",
  summary: "移除自由模式生成入口，补齐记忆快照的提交与恢复链路，强化物品状态约束、可解释检索和遗忘机制，并完善存档删除及终局、时间线异常处理。",
  developer: "Codex",
  areas: ["backend", "frontend", "campaign", "memory", "timeline", "tests"],
  changes: [
    "本次记录对应提交 36b482c 与 84efc73；记忆机制与兼容边界详见 docs/campaign_memory.md。",
    "只保留战役生成：POST /sessions 未传 campaign_filename 时使用 default_campaign.json；显式空值、空字符串和非法文件名返回 422，文件不存在返回 404，且不会留下空会话。移除前端自由模式选项和后端单模型回退。",
    "保留旧自由会话与时间线的读取能力，但继续生成返回 422；首页恢复旧自由会话时改为创建默认战役，不将旧历史静默改写成战役数据。",
    "统一最终回合的记忆采集顺序：先完成结局替换和物品状态校验，再采集叙事与结构化后果；固定开场和本地 Examiner 拒绝也进入记忆链路。",
    "原始记忆缓冲与 version/pending 随剧情节点一起落库。后台摘要使用独立控制器副本，并捕获当前分支、当前幕的对话；写回时在事务内比较活动节点及记忆版本，仅更新记忆字段，拒绝迟到或重复结果。",
    "切换存档或恢复分支时取消旧维护任务并清理缓存；下一回合等待本会话维护完成。服务重启后的 pending 快照在构建提示词前重试，摘要失败保留输入，允许后续继续恢复。",
    "分层摘要只在上层生成成功后消费原始缓冲或低层摘要；L2、L3 晋级可独立重试，L3 达到阈值后继续压缩。运行时摘要不再写入缺少分支隔离的全局知识库，跨幕清理保留物品状态与显式别名。",
    "SCORE 同时校验 items_gained/items_lost 与 memory_updates 物品更新，同回合删除优先；丢失或销毁状态不会被普通获得事件覆盖。明确找回、修复分别使用 transition: recovered、transition: repaired，名称归一化并支持显式 aliases，不猜测语义同义词。",
    "被拒绝的物品获得事件在状态合并前移除，背包与 Director 使用真实物品状态，摘要输入附带权威状态。该约束作用于结构化输出，不代表已经完成对任意叙事文本的事实审查。",
    "记忆查询补充地点、人物、任务、物品、线索和近期事件；MemoryHit 提供分项得分与命中原因，按来源、内容及跨层回合范围去重。恢复快照后按需批量补齐向量，向量服务不可用时退回实体和关键词排序。",
    "只有实际完整进入最终提示词的记忆才记录召回并强化；未注入的竞争记忆持久化抑制系数，后台维护本身不产生召回。补齐数值稳定、同回合去重、召回历史上限与旧轮次换算，关键后果摘要的保护标记随晋级继承。",
    "记忆检索明细以 narrative_memory 类型保存到 model_outputs.retrieved_chunks_json，便于追查某回合实际使用了哪些记忆；当前检索权重仍是待质量评估的工程默认值。",
    "存档删除后端按槽 id 精确执行并保护当前活动存档；禁用提示和二次确认目前位于未挂载的 SidePanel，尚需接入首页实际使用的 SettingsMenu，不能视为页面入口已交付。此处承接 9 月 18 日存档删除记录。生成遇到 HTTP 409 时重新读取最新会话、活动节点与剧情输出，避免继续使用过期节点。",
    "终局判定支持中文冒号前带决定标签的明确行动，排除假设性提问；最终场景不再因回合预算耗尽而越过最后一幕，兼容已保存的越界终局进度。前端状态展示及相关提示文案统一使用血条称呼。",
    "提交前验证记录：完整工作区后端 437 项测试、前端 14 项测试及 TypeScript 类型检查通过；记忆改动的独立暂存快照后端 428 项通过，两组数量对应不同文件范围，不应相加。",
    "记忆改动另完成前端生产构建及桌面、移动端入口检查；入口检查使用模拟 API。200 回合测试为离线层级摘要回归，覆盖失败重试、恢复、去重、物品状态和数值稳定，不代表真实模型下的长剧情质量或全部结局路线已经验证。",
  ],
  relatedFiles: [
    "docs/campaign_memory.md",
    "backend/app/routers/sessions.py",
    "backend/app/routers/slots.py",
    "backend/app/database/timeline.py",
    "backend/app/services/scenario_generator/generator.py",
    "backend/app/services/scenario_generator/memory_lifecycle.py",
    "backend/app/services/scenario_generator/agent_pipeline.py",
    "backend/app/services/memory/memory_controller/controller.py",
    "backend/app/services/memory/memory_controller/maintenance.py",
    "backend/app/services/memory/nsb/branch.py",
    "backend/app/services/memory/nsb/retrieval.py",
    "backend/app/services/memory/score_tracker.py",
    "backend/app/services/memory/forgetting.py",
    "backend/app/services/campaign_endings.py",
    "backend/tests/test_memory_consistency.py",
    "backend/tests/test_campaign_openings.py",
    "backend/tests/test_campaign_ending_selection.py",
    "backend/tests/test_campaign_wiring.py",
    "frontend/src/components/game/useGameActions.ts",
    "frontend/src/components/game/useGameEffects.ts",
    "frontend/src/components/game/SidePanel.tsx",
  ],
  nextSteps: [
    "用独立存档开展真实模型长剧情评估，记录关键事实召回率、错误复活物品、跨分支污染、摘要成本与下一回合等待时间，再调整检索和遗忘参数。",
    "补充叙事文本与结构化物品状态不一致的质量检查，明确检测、重试和降级策略，避免把结构化校验等同于全文事实校验。",
    "增加前端时间线冲突后刷新失败、连续切档及后台摘要迟到的端到端覆盖，并持续验证各战役最终选择到持久化结局的完整链路。",
  ],
};
