import type { DevLogEntry } from "@/lib/dev-log/types";

export const entry: DevLogEntry = {
  id: "2026-09-15-branching-timeline-and-real-llm-smoke",
  date: "2026-09-15",
  title: "可分叉剧情时间线与四战役真实 LLM 跨幕回归",
  summary: "把线性历史升级为可恢复、可继续分叉的剧情树，并用当前 DeepSeek 配置完成四个内置战役的开场、续写和跨幕真实模型回归，修复 Examiner 误拦截和旧幕上下文回流。",
  developer: "Codex",
  areas: ["backend", "frontend", "timeline", "campaign", "llm", "tests"],
  changes: [
    "新增 story_turns 快照表和 active_turn_id，将每次玩家行动、结构化输出、完整游戏状态、Campaign 进度、模型及来源保存为不可变剧情节点。",
    "生成回合按当前节点建立子节点，并使用 expected_parent_id 与会话级锁阻止过期分支并发覆盖当前进度。",
    "新增剧情树列表、节点详情和节点激活 API；恢复旧节点时同步恢复 game_state、Campaign 进度、存档槽、记忆控制器快照和当前分支消息视图。",
    "前端时间线增加树状分支、剧情与状态详情、当前路径标记和『从此处继续』操作；回到游戏后，新行动会从恢复节点形成新分支，旧后代仍保留。",
    "最近对话读取限制在当前时间线祖先链，并在 Campaign 模式进一步限制到当前幕；上一幕内容只通过 recap 提供，避免旧幕原始叙事压过新幕开场。",
    "Director 现在同时接收当前地点、当前幕固定开场、当前幕最近记录和明确标注为背景的上一幕 recap，Narrator 必须从当前幕继续。",
    "纯续写动作『继续』『继续剧情』『接着』确定性放行，不再因 entry_state 未重复列出开场人物而被 Examiner 错误阻止；具体动作仍走完整规则判定。",
    "新增四战役 transition smoke 脚本，通过临时两回合副本走真实 HTTP 与 LLM 路径，记录每步提示词、地点、人物、剧情、来源、模型和连续性检查，测试后自动清理副本。",
    "真实模型验证使用当前配置 deepseek-chat：卡塞尔入学档案、火之晨曦、悼亡者之瞳、白王降临均完成『开场→继续→下一幕开场→继续』，未发现入学调查串入、开场重复或跨幕回跳。",
    "验证：合并最新 master 后，后端完整测试 321 项通过；前端生产构建与 TypeScript 检查通过；最终真实 LLM 冒烟报告位于 artifacts/smoke/campaign-transition-smoke-20260915-165635.md。",
  ],
  relatedFiles: [
    "backend/app/database/timeline.py",
    "backend/app/database/schema.py",
    "backend/app/database/sessions.py",
    "backend/app/services/scenario_generator/generator.py",
    "backend/app/services/scenario_generator/agent_pipeline.py",
    "backend/app/services/scenario_generator/prompting.py",
    "backend/app/services/agents/examiner.py",
    "backend/app/services/agents/director.py",
    "backend/tests/test_branching_timeline.py",
    "backend/tests/test_campaign_openings.py",
    "frontend/src/app/timeline/StoryTimeline.tsx",
    "frontend/src/app/timeline/useTimelineData.ts",
    "frontend/src/components/game/useGameActions.ts",
    "docs/branching_timeline.md",
    "README.md",
    "scripts/campaign_transition_smoke.py",
    "artifacts/smoke/campaign-transition-smoke-20260915-165635.md",
  ],
  nextSteps: [
    "用更长的真实 Campaign 分支验证多次回退、再分叉和跨 Arc 后的 recap、锚点及 NPC 关系恢复。",
    "为时间线节点增加用户可编辑标签和分支命名，便于大型战役定位关键选择。",
    "把真实 LLM 冒烟测试接入可选的手动发布检查，避免在普通 CI 中消耗模型额度。",
  ],
};
