import type { DevLogEntry } from "@/lib/dev-log/types";

export const entry: DevLogEntry = {
    id: "2026-06-24-campaign-runtime-slots-and-local-workflow",
    date: "2026-06-24",
    title: "Campaign Runtime 接线、存档槽隔离和本地工作流整理",
    summary: "修复 Campaign 运行时进度、锚点揭示、全局 manager 串线和存档槽混用问题；补齐已实现模块在主流程中的实际接线，并整理本地启动、清理和开发日志展示。",
    developer: "zjr",
    areas: ["backend", "frontend", "campaign", "save-slots", "rag", "developer-tooling"],
    changes: [
      "CampaignProgress 增加 turn_in_session 并在生成成功后递增，session/arc 自动推进时重置，避免 30 回合切换、recap 注入和完整 Arc 推进失效。",
      "锚点候选在成功生成后写入 revealed_anchors，动态锚点也接入主流程，Timeline 不再长期为空。",
      "CampaignManager 改为按 session_id + slot_name 加载和缓存，避免全局单例导致新战役覆盖旧会话或自由模式继承战役上下文。",
      "主流程接入 EmbeddingClient、HealthMonitor、动态锚点生成、LLM fact extraction、token section 截断和最近对话历史注入。",
      "存档槽 API 和前端下拉框改为按当前 sessionId 过滤，避免多个历史 default (A1S1 · T0) 混在当前会话里。",
      "新增存档槽加载接口，选择 slot 会切换对应 session/state/model；新建 slot 会复制并绑定当前会话的 Campaign progress。",
      "新增本地 setup/start/clean 脚本，并将 Codex 环境动作接到这些脚本，减少重复手动命令。",
      "开发日志字段升级为 developer，并在页面上明确显示每次开发工作的开发人员。",
    ],
    relatedFiles: [
      "backend/app/main.py",
      "backend/app/database.py",
      "backend/app/schemas/campaign.py",
      "backend/app/schemas/game.py",
      "backend/app/services/campaign_manager.py",
      "backend/app/services/scenario_generator.py",
      "backend/app/services/prompt_builder.py",
      "backend/app/services/retriever.py",
      "backend/app/services/context_strategy.py",
      "backend/app/services/health_monitor.py",
      "backend/tests/test_campaign_runtime_wiring.py",
      "backend/tests/test_campaign_wiring.py",
      "frontend/src/app/page.tsx",
      "frontend/src/app/dev-log/DevLogView.tsx",
      "frontend/src/lib/api.ts",
      "frontend/src/lib/dev-log.ts",
      "frontend/src/types.ts",
      "scripts/setup_local.sh",
      "scripts/start_backend.sh",
      "scripts/start_frontend.sh",
      "scripts/start_local.sh",
      "scripts/clean_local.sh",
    ],
    nextSteps: [
      "用真实战役连续运行超过 30 个 campaign turn，确认 recap、session advance 和 revealed_anchors 在 UI 中稳定同步。",
      "检查存档槽加载是否需要复制/恢复完整 game_state 快照，而不只是切换 Campaign progress。",
      "根据真实 playtest 数据校准 HealthMonitor baseline。",
    ],
  };
