import type { DevLogEntry } from "@/lib/dev-log/types";

export const entry: DevLogEntry = {
  id: "2026-09-15-campaign-openings-and-llm-errors",
  date: "2026-09-15",
  title: "四个战役独立开场、续写上下文与请求错误提示修复",
  summary: "修复战役进入和首次续写沿用报到大厅剧情的问题，统一战役入口、初始状态和跨幕开场，并细分 LLM 请求失败提示。",
  developer: "zjr",
  areas: ["backend", "frontend", "campaign", "llm", "tests"],
  changes: [
    "四个战役分别从学院大门、婶婶家卧室、苏菲拉德披萨馆和黑天鹅港开场，补充各幕 entry_state 地点及首幕人物、物品、目标和背景提示。",
    "新战役使用独立初始状态，清除自由模式的报到大厅、诺诺接应和入学任务残留；starting_state 支持空列表和零值覆盖，跨幕时保留累计体力和物品。",
    "前端初始化先显示剧情读取状态，所有战役及时间线入口统一自动请求开场；复用启动请求，避免 React Strict Mode 重复创建会话。",
    "会话响应返回 campaign_filename，刷新和加载存档时恢复战役选择与历史剧情；已有剧情不重复播放开场，无历史的战役自动进入对应场景。",
    "战役续写移除固定入学调查限制，注入当前战役名称、限制和本幕开场背景，要求承接最近行动并保持时间、地点和人物连续。",
    "开场判断改用当前幕 turn_in_session，正常推进到下一幕后可读取该幕开场，不再依赖全局 turn 为零。",
    "生成期间禁用重复操作并增加请求防重入；背景跟随地点与提示词更新，切换场景时清除旧背景。",
    "LLM 错误提示区分连接失败、超时、认证、余额、权限、限流和服务异常，避免将网络错误统一归因为 API Key 或余额问题。",
    "叙事输出长度要求从约 30 句调整为约 20 句。",
    "验证：128 项相关后端测试、前端 TypeScript 检查通过；隔离浏览器验证四战役开场、继续、刷新、切换、新建会话和时间线入口。续写使用模拟模型返回，尚未验证真实 LLM 生成内容。",
  ],
  relatedFiles: [
    "backend/app/routers/sessions.py",
    "backend/app/services/game_state/entry_state.py",
    "backend/app/services/scenario_generator/opening_scene.py",
    "backend/app/services/campaign_context.py",
    "backend/app/services/llm_client/errors.py",
    "backend/app/services/prompt_builder/builder.py",
    "backend/data/campaigns/default_campaign.json",
    "backend/data/campaigns/龙族Ⅰ_火之晨曦_campaign.json",
    "backend/data/campaigns/龙族Ⅱ_悼亡者之瞳_campaign.json",
    "backend/data/campaigns/龙族Ⅲ_黑月之潮_campaign.json",
    "backend/tests/test_campaign_openings.py",
    "frontend/src/components/game/useGameActions.ts",
    "frontend/src/components/game/useGameEffects.ts",
    "frontend/src/components/game/useGameSession.ts",
    "frontend/src/components/game/useSceneBackground.ts",
    "frontend/src/lib/game/initialOutput.ts",
  ],
  nextSteps: [
    "用真实模型验证四个战役的首段续写和连续跨幕叙事，检查是否仍有入学剧情串入。",
    "已有存档保留历史剧情与进度；验证新开场时重新选择战役或新建会话。",
  ],
};
