export type DevLogEntry = {
  id: string;
  date: string;
  title: string;
  summary: string;
  author: string;
  areas: string[];
  changes: string[];
  relatedFiles: string[];
  nextSteps?: string[];
};

export const devLogEntries: DevLogEntry[] = [
  {
    id: "2026-06-22-prompt-refactor-experiment",
    date: "2026-06-22",
    title: "Prompt 重构验证实验",
    summary: "基于 6 轮实验（L0/L1/L2）识别出 prompt 设计为主要瓶颈后，对系统 prompt 进行深度重构：降低 temperature、精简 JSON schema、调整 L0 卡片位置、清理措辞，并设计三条件对照实验验证效果。",
    author: "TandyBlow",
    areas: ["backend", "frontend", "llm", "prompt", "experiment"],
    changes: [
      "LLM temperature 从 0.9 降至 0.3，减少非 JSON 输出和随机漫步。",
      "Baseline JSON schema 精简为 8 字段（去掉 5 个状态追踪字段：sanity_delta、health_delta、items_update、npcs_update、quests_update），降低模型输出负担。",
      "L0 模式：8+5 字段 JSON（状态追踪字段标记为可选），L0 卡片从 prompt 顶部移至底部（叙事指令之后、JSON 格式之前），避免位置污染叙事指令。",
      "系统 prompt 措辞清理：DM→KP、删除冗余说明、强化 JSON 格式约束。",
      "评估方案：三步模糊匹配（规范化 + 关键词 + 嵌入相似度），评估叙事质量、状态追踪准确性和 JSON 合规率。",
      "前端新增战役选择器（campaign selector dropdown），支持从 Timeline 页面跳转时自动带入战役文件名。",
      "前端 createSession 支持 campaign/arc/session 参数，战役模式下自动触发开场生成。",
      "后端 POST /sessions 修复 entry_state 合并逻辑：不再仅 mid-campaign 合并，所有战役模式统一合并 entry_state（含 starting_state）。",
      "后端 /campaigns 列表过滤：跳过 schema 文件、下划线前缀调试文件、无 arcs 字段的非法 campaign。",
      "CORS 增加 localhost:3001 允许源，支持多前端开发端口。",
    ],
    relatedFiles: [
      "backend/app/main.py",
      "backend/app/services/llm_client.py",
      "backend/app/services/prompt_builder.py",
      "backend/app/services/scenario_generator.py",
      "backend/app/services/campaign_generator.py",
      "frontend/src/app/page.tsx",
      "frontend/src/lib/api.ts",
      "frontend/src/types.ts",
      "frontend/src/lib/dev-log.ts",
    ],
    nextSteps: [
      "运行 Baseline-new / L0-bot-full-new / L1-mix-k5-new 三条件各 10 轮（A+B 场景各 5 轮），收集 LLM 输出。",
      "用三步模糊匹配方案评估新旧数据，确认 prompt 改动是否提升 JSON 合规率和叙事质量。",
      "若 JSON 合规率显著提升，考虑将精简 schema 作为默认配置；否则回退部分字段。",
    ],
  },
  {
    id: "2026-06-19-campaign-wiring-and-novel-pipeline",
    date: "2026-06-19",
    title: "Campaign Wiring 集成测试与小说管线脚本",
    summary: "完成 Campaign 系统 API 接线验证的集成测试框架，新增小说→战役自动生成管线脚本，修复 lazy imports 和 from __future__ 兼容性问题，为 Phase 6 执行做准备。",
    author: "TandyBlow",
    areas: ["backend", "campaign", "testing", "pipeline", "knowledge-base"],
    changes: [
      "新增 backend/tests/test_campaign_wiring.py — Campaign load→opening→inject→anchor 全链路集成测试（WIRE-05）。",
      "新增 scripts/run_novel_pipeline.py — TXT→campaign.json 自动生成管线脚本，支持编码检测、章节提取、锚点生成、跨章组装。",
      "全局移除 `from __future__ import annotations` 导入，修复 lazy imports 导致的类型解析问题。",
      "新增 backend/tests/test_no_future_annotations.py — 静态检查确保不再引入 from __future__ import annotations。",
      "知识库大幅扩展 world_lore.md：新增蛇岐八家、猛鬼众、黑天鹅港·δ计划、言灵体系、皇与鬼等 5 个龙族世界观条目。",
      "知识库 npcs.json 扩展：新增日本分部相关 NPC（源稚生、源稚女/风间琉璃、上杉越、绘梨衣、赫尔佐格等）及关系网络。",
      "知识库 locations.json 扩展：新增日本场景（源氏重工、极乐馆、黑天鹅港等）。",
      "龙族 I/II/III 共 6 本 TXT 源文件就位（~4.5MB），为 Phase 8 内容创建做准备。",
      "campaign_generator.py 新增 NovelIngestor 类——编码检测 + 章节边界识别 + 逐章锚点提取 + 跨章组装 pipeline。",
    ],
    relatedFiles: [
      "backend/tests/test_campaign_wiring.py",
      "backend/tests/test_no_future_annotations.py",
      "scripts/run_novel_pipeline.py",
      "backend/app/services/campaign_generator.py",
      "backend/app/main.py",
      "knowledge/world_lore.md",
      "knowledge/npcs.json",
      "knowledge/locations.json",
      "13802-龙族Ⅰ_火之晨曦.txt",
      "13803-龙族Ⅱ_悼亡者之瞳.txt",
      "13804-龙族Ⅲ+_+黑月之潮（上）.txt",
      "13805-龙族Ⅲ+_+黑月之潮（中）.txt",
      "13806-龙族Ⅲ+_+黑月之潮（下）.txt",
      "13807-龙族Ⅳ_奥丁之渊.txt",
    ],
    nextSteps: [
      "执行 Phase 6 四个计划（06-01~06-04）：Campaign Wiring → Session Auto-Advance → Arc Selection API → Arc Selection UI。",
      "Phase 6 完成后运行 auto_play.py 270 回合验证，确认 session 边界自动触发 recap + FSM 切换。",
      "小说管线需 charset-normalizer 依赖安装后才能端到端测试（NOVEL-01）。",
    ],
  },
  {
    id: "2026-06-18-campaign-engine-v1-complete",
    date: "2026-06-18",
    title: "Campaign Narrative Engine v1 完成 — 5 阶段 18 计划 143 测试",
    summary: "经过 5 个阶段的系统化执行，Jity Campaign Narrative Engine v1 正式完成。实现了从基础技术栈升级到 AI 战役生成、锚点事件系统、叙事健康监控的完整闭环，auto_play.py 270 回合无崩溃通过。",
    author: "TandyBlow",
    areas: ["backend", "frontend", "campaign", "llm", "rag", "testing", "ui", "milestone"],
    changes: [
      "Phase 1 Foundation（4 plans）：FastAPI/Pydantic/FAISS 升级、openai SDK 替换 httpx + json_repair、tiktoken token 计数、transitions FSM、Tailwind CSS v4 + shadcn/ui。",
      "Phase 2 Campaign Core（5 plans）：campaign.json 标准化格式 + v1→v2→v3 迁移链、CampaignManager 加载/校验/开场覆盖、独立 campaign_progress 表 + FSM 集成、锚点事件系统（混合触发器 + 单锚点/回合 + 冷却）、CampaignManager 上下文注入 + token 预算检查。",
      "Phase 3 Narrative Quality（4 plans）：Session 前情提要（LLM 压缩 'Previously on...'）、AI 战役生成（deepseek-v4-pro）+ 前端策展编辑器、动态分支检测（LLM fact extraction 替代硬编码关键词）、叙事健康监控 + 隐式引导注入。",
      "Phase 4 UI & Polish（2 plans）：发现时间线 UI（system-known vs player-confirmed 区分）、策展编辑器增强。",
      "Phase 5 Pre-Launch Hardening（3 plans）：context_strategy 接口、RAG embedding 升级（hash-based → DeepSeek embedding API）、选项策略配置化、并发安全（乐观锁）、auto_play.py 270 回合验证通过（3 arcs × 3 sessions × 30 turns）。",
      "schemas/ 包拆分：game.py（144 行）+ campaign.py（179 行），从单一 300+ 行文件重构。",
      "PromptBuilder 重构：PromptInput dataclass（6 参数→1 参数）、消息历史注入、风格锚点、负面约束指令。",
      "143 个 pytest 测试全部通过，覆盖 CampaignManager、FSM、锚点系统、schema 迁移、token 预算、前情提要、fact extraction、健康监控。",
      "DeepSeek 模型迁移：deepseek-chat → deepseek-v4-flash（日常）/ deepseek-v4-pro（创意生成）。",
    ],
    relatedFiles: [
      "backend/app/services/campaign_manager.py",
      "backend/app/services/campaign_fsm.py",
      "backend/app/services/campaign_generator.py",
      "backend/app/services/scenario_generator.py",
      "backend/app/services/prompt_builder.py",
      "backend/app/services/llm_client.py",
      "backend/app/services/game_state.py",
      "backend/app/services/retriever.py",
      "backend/app/services/embedding_client.py",
      "backend/app/services/health_monitor.py",
      "backend/app/services/context_strategy.py",
      "backend/app/schemas/game.py",
      "backend/app/schemas/campaign.py",
      "backend/tests/*.py",
      "frontend/src/app/curator/page.tsx",
      "frontend/src/app/timeline/page.tsx",
      "frontend/src/app/page.tsx",
      "scripts/auto_play.py",
    ],
    nextSteps: [
      "进入 v1.5（Phase 6-8）：Session 自动推进 + Arc 选择 + 小说管线 + 龙族内容包。",
      "解决已知 Blocker：Campaign 系统端到端 HTTP 验证、session_messages 表结构调整、_is_first_turn_of_session() 修复。",
    ],
  },
  {
    id: "2026-06-17-auto-play-script",
    date: "2026-06-17",
    title: "自动跑剧情脚本和长轮次记录",
    summary: "新增自动剧情 playtest 脚本，用于连续创建会话、自动选择更能推进剧情的选项，并把每轮生成内容、选择记录、Context Memory 和 RAG Hits 追加到 Markdown 日志中，方便做 300 轮 x 3 次的稳定性观察。",
    author: "Codex",
    areas: ["developer-tooling", "playtest", "backend", "llm"],
    changes: [
      "新增 scripts/auto_play.py，默认运行 3 个 session，每个 session 最多 300 轮，达到轮次后重新开始新会话。",
      "脚本会记录每轮所有可选项、实际选中的选项、选择分数、生成剧情、NPC 对话、状态变化、Context Memory 快照和 RAG Hits。",
      "自动选项策略偏向推进、继续、前往、调查、询问、检查、任务、地点、关键 NPC 或关键物品，并降低等待、拒绝、逃跑、沉默等被动选项权重。",
      "脚本按轮追加写入 Markdown 文件，默认输出到 playtest_logs/，即使长跑中断也能保留已经生成的内容。",
      "为生成请求增加 retries 参数，遇到临时网络或模型接口错误时会短暂等待并重试，降低长跑被偶发错误打断的概率。",
      "README 增加自动跑剧情的默认长跑命令、小规模试跑命令和常用参数说明。",
      "将 playtest_logs/ 加入 .gitignore，避免 900 轮剧情日志误提交到仓库。",
      "为了支持长剧情轮次，把提示词叙事目标调整为约 30 句，并提高 LLM max_tokens 上限。",
      "更新旧版 config.example.js 的示例模型名，保持示例配置和当前长文本生成需求一致。",
    ],
    relatedFiles: [
      "scripts/auto_play.py",
      "README.md",
      ".gitignore",
      "backend/app/services/llm_client.py",
      "backend/app/services/prompt_builder.py",
      "config.example.js",
      "frontend/src/lib/dev-log.ts",
    ],
    nextSteps: [
      "先用 --runs 1 --turns 5 做小规模试跑，确认输出格式和后端连接正常。",
      "再运行默认 3 x 300 轮长跑，检查日志里是否出现重复循环、记忆漂移、RAG 误命中或 JSON 修复失败。",
    ],
  },
  {
    id: "2026-06-16-status-delta-and-json-repair",
    date: "2026-06-16",
    title: "状态变化提示、血统稳定恢复和 JSON 修复",
    summary: "增强游戏回合反馈和 AI 输出可靠性：前端直接提示本回合血统稳定/体力变化，后端统一处理血统稳定的自动恢复，并为模型 JSON 输出增加强制格式和二次修复。",
    author: "Codex",
    areas: ["backend", "frontend", "llm", "game-state"],
    changes: [
      "在主控制台剧情选项前新增状态变化提示，显示血统稳定和体力的本回合增减及对应原因说明。",
      "新增状态提示样式，区分损耗和恢复，让玩家更容易理解行动代价。",
      "后端状态合并时加入每回合 2 点血统稳定自动恢复，并在提示词中说明模型不要把自动恢复写入 sanity_delta。",
      "LLM 请求改用 response_format=json_object，并把最大输出 token 提升到 5000，减少剧情 JSON 被截断的概率。",
      "当模型输出首次解析失败时，自动发起一次 JSON 修复请求；若仍失败，会把原始输出和修复输出一并保存，方便排查。",
      "提示词增加字符串转义约束，要求对白引用避免未转义英文双引号，降低 JSON 解析错误。",
    ],
    relatedFiles: [
      "backend/app/services/game_state.py",
      "backend/app/services/llm_client.py",
      "backend/app/services/prompt_builder.py",
      "frontend/src/app/page.tsx",
      "frontend/src/app/globals.css",
      "frontend/src/lib/dev-log.ts",
    ],
    nextSteps: [
      "用真实 DeepSeek 输出连续跑几回合，确认状态提示、自动恢复和模型返回的 sanity_delta 不会重复计算。",
      "观察 model_outputs 中的失败记录，判断 JSON 修复提示是否还需要补充字段类型或截断处理规则。",
    ],
  },
  {
    id: "2026-06-15-context-memory",
    date: "2026-06-15",
    title: "第二阶段：强化 Context Memory",
    summary: "把原本偏临时记录的状态扩展成真正的游戏记忆系统：明确长期状态结构、稳定 NPC/任务/物品字段，并让每轮 AI 输出只提交增量记忆，由后端合并成下一轮 prompt 的上下文。",
    author: "Codex",
    areas: ["backend", "frontend", "game-state", "prompt"],
    changes: [
      "明确 state schema，补齐 current_location、items、npcs、quests、recent_events、world_facts 和 player_status。",
      "新增 ItemMemory、NPCMemory、QuestMemory、WorldFactMemory、PlayerStatus 和 MemoryUpdates 等结构化 schema。",
      "为 NPC、任务、物品和长期事实统一稳定字段，例如 name、status、description、relationship、objective、notes、source。",
      "后端状态合并改为 upsert/remove 规则：AI 只通过 memory_updates 提供本回合新增或变化的记忆，系统负责回合数、血统稳定、体力裁剪、状态归一化和去重合并。",
      "增加 world_facts 的系统推断规则，用于记录红色标记、L-13 编号、S级观察对象、执行部观察等关键长期事实。",
      "recent_events 改为保存 key_event 或自动摘要，限制最多 8 条、单条最多 120 字，避免把长篇 narration 无限塞进状态。",
      "Prompt 中拆分当前状态、Context Memory/长期记忆和最近事件，下一轮生成会带上当前位置、同行 NPC、任务、关键物品、长期事实和玩家状态。",
      "前端右侧 Context Memory 改成当前状态、同伴与 NPC、关键物品、任务、长期事实、最近事件等清晰分区。",
    ],
    relatedFiles: [
      "backend/app/schemas.py",
      "backend/app/services/game_state.py",
      "backend/app/services/prompt_builder.py",
      "frontend/src/app/page.tsx",
      "frontend/src/types.ts",
      "frontend/src/lib/dev-log.ts",
    ],
    nextSteps: [
      "连续生成多轮，确认当前地点、同行 NPC、正在进行任务、关键物品和最近事件都能稳定保留。",
      "检查下一轮 prompt 中的 Context Memory 是否只包含必要摘要，没有重复堆叠整段剧情文本。",
    ],
  },
  {
    id: "2026-06-15-knowledge-base-and-rag",
    date: "2026-06-15",
    title: "第三阶段：扩充 Knowledge Base 和 RAG",
    summary: "把知识库从单一样例扩展为按类型组织的 RAG 数据源，并增强轻量检索、结果落库和前端命中展示，为项目报告中的 RAG 演示打基础。",
    author: "Codex",
    areas: ["backend", "frontend", "rag", "knowledge-base"],
    changes: [
      "将知识库拆分为 npcs.json、locations.json、quests.json、rules.md 和 world_lore.md，并保留 cassell_lore.json 兼容已有样例。",
      "JSON 与 Markdown chunk 支持 source_type、keywords、title、content 和 importance，Markdown 可在标题后写元数据。",
      "KnowledgeBase 加载时跳过 README，自动解析 Markdown 元数据，并根据文件名推断 npc、location、quest、rule、world_lore 等来源类型。",
      "轻量检索增加中文 2-4 字 n-gram token 展开、关键词命中加权、标题命中加权和 importance 加权，提升临时通行卡、诺诺、图书馆等短查询命中率。",
      "ScenarioGenerator 会把本轮 retrieved_chunks 序列化写入 model_outputs，成功和失败输出都能追溯当时用了哪些知识。",
      "RAG Hit 返回内容增加 keywords 和 importance，前端展示来源类型、分数、标题、短内容和关键词 chip。",
      "更新 knowledge/README.md，说明知识库文件职责、JSON 字段和 Markdown 元数据格式。",
    ],
    relatedFiles: [
      "backend/app/database.py",
      "backend/app/schemas.py",
      "backend/app/services/knowledge_base.py",
      "backend/app/services/retriever.py",
      "backend/app/services/scenario_generator.py",
      "frontend/src/app/page.tsx",
      "frontend/src/types.ts",
      "knowledge/README.md",
      "knowledge/cassell_lore.json",
      "knowledge/locations.json",
      "knowledge/npcs.json",
      "knowledge/quests.json",
      "knowledge/rules.md",
      "knowledge/world_lore.md",
      "frontend/src/lib/dev-log.ts",
    ],
    nextSteps: [
      "用“临时通行卡”“诺诺”“图书馆”等输入做检索验收，确认 RAG Hits 能命中对应 NPC、地点、规则或任务资料。",
      "继续观察轻量哈希检索的误命中情况，后续再评估是否接入真正 embedding 服务。",
    ],
  },
  {
    id: "2026-06-13-scripted-opening-and-dev-log",
    date: "2026-06-13",
    title: "固定开场、AI 接管节点和开发日志",
    summary: "把游戏开场整理成可控的固定剧情，引导玩家进入三个调查方向；同时新增开发日志页面，方便记录后续代码改动。",
    author: "Codex",
    areas: ["backend", "frontend", "story", "developer-tooling"],
    changes: [
      "新增卡塞尔学院报到处大厅固定开场，并为三个初始玩家反应提供脚本化输出。",
      "固定开场结束后交给 AI 继续生成；未配置 DeepSeek API key 时返回 503，避免后续剧情继续使用本地兜底内容。",
      "更新提示词约束和 LLM 输出归一化，要求物品、NPC、任务等字段使用对象数组。",
      "调整前端初始剧情、默认行动和错误提示展示，移除 narrative_profile 请求字段。",
      "新增 STORY_OUTLINE.md，说明固定剧情结构、AI 接管节点和建议延展方向。",
      "新增 /dev-log 路由、结构化日志数据和主控制台入口，集中展示开发改动。",
      "生产环境默认隐藏开发日志页面，可通过 ENABLE_DEV_LOG=true 显式开启。",
    ],
    relatedFiles: [
      "STORY_OUTLINE.md",
      "backend/app/main.py",
      "backend/app/schemas.py",
      "backend/app/services/game_state.py",
      "backend/app/services/llm_client.py",
      "backend/app/services/prompt_builder.py",
      "backend/app/services/scenario_generator.py",
      "frontend/src/app/dev-log/page.tsx",
      "frontend/src/app/dev-log/DevLogView.tsx",
      "frontend/src/lib/dev-log.ts",
      "frontend/src/app/page.tsx",
      "frontend/src/app/globals.css",
      "frontend/src/lib/api.ts",
    ],
    nextSteps: [
      "配置 DeepSeek API key 后，从三个主调查方向各跑一轮，检查 AI 接管后的结构化输出质量。",
      "每次完成一组有意义的代码改动后，在 devLogEntries 顶部新增一条记录。",
    ],
  },
];
